# Run flyctl launch to add an app name
[[services]]
  internal_port = 8080
  protocol = "TCP"

  [services.port]

    [services.port.443]
      handlers = ["tls", "http"]

    [services.port.80]
      handlers = ["http"]
